version: '3.3'

volumes:
  snipeit-data:
    driver: local

networks:
  snipeit-network:
    driver: bridge

services:
  # Optional internal Redis to avoid external dependency
  # redis:
  #   image: redis:7-alpine
  #   container_name: snipeit-redis
  #   restart: unless-stopped
  #   networks:
  #     - snipeit-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.overlay
      args:
        # Pin to Snipe-IT version matching your codebase. Try v8.3.3; if not found, use latest.
        SNIPE_IT_TAG: v8.3.3
    image: custom-snipe-it:8.3.3-overlay
    container_name: snipeit-app
    restart: unless-stopped
    ports:
      - "8008:80"
    env_file:
      - .env.dc
    environment:
      # PHP overrides (image also loads php-custom.ini we baked-in)
      PHP_MEMORY_LIMIT: 2G
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_POST_MAX_SIZE: 100M
      # If you enable internal redis service above, set:
      # REDIS_HOST: redis
      # REDIS_PORT: 6379
      # SESSION_DRIVER: redis
      # CACHE_DRIVER: redis
    volumes:
      # Persist Snipe-IT app data outside container
      - ./data/snipeit:/var/lib/snipeit
      # Persist Laravel storage (logs, cache, files)
      - ./data/storage:/var/www/html/storage
      # Persist public uploads (images, logos, attachments)
      - ./data/uploads:/var/www/html/public/uploads
    networks:
      - snipeit-network
