version: '3.8'

services:
  app-custom:
    build:
      context: .
      dockerfile: Dockerfile.custom-apache
    image: snipeit-custom-apache:latest
    container_name: snipeit-app-apache
    restart: unless-stopped
    ports:
      - "8009:80"
    env_file:
      - .env.dc
    environment:
      PHP_MEMORY_LIMIT: 2G
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_POST_MAX_SIZE: 100M
    volumes:
      - ./data/snipeit:/var/lib/snipeit
      - ./data/storage:/var/www/html/storage
      - ./data/uploads:/var/www/html/public/uploads

  scheduler:
    image: snipeit-custom-apache:latest
    container_name: snipeit-scheduler
    restart: unless-stopped
    depends_on:
      - app-custom
    env_file:
      - .env.dc
    command: ["php", "/var/www/html/artisan", "schedule:work"]
    volumes:
      - ./data/snipeit:/var/lib/snipeit
      - ./data/storage:/var/www/html/storage
      - ./data/uploads:/var/www/html/public/uploads
